"""add name, purpose, key_suffix to api_keys

Revision ID: 08ae34721e7a
Revises: 8a0840b43ad6
Create Date: 2026-08-31 12:02:57.058403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ae34721e7a'
down_revision: Union[str, Sequence[str], None] = '8a0840b43ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('api_keys', sa.Column('purpose', sa.String(length=500), nullable=True))
    op.add_column('api_keys', sa.Column('key_suffix', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'key_suffix')
    op.drop_column('api_keys', 'purpose')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
