"""make usage_log api_key_id nullable

Revision ID: 8a0840b43ad6
Revises: e288a962fa94
Create Date: 2026-08-31 11:15:58.319972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0840b43ad6'
down_revision: Union[str, Sequence[str], None] = 'e288a962fa94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
