"""add password_hash to tenants

Revision ID: e288a962fa94
Revises: b42484e5f106
Create Date: 2026-08-31 11:04:53.815041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e288a962fa94'
down_revision: Union[str, Sequence[str], None] = 'b42484e5f106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'password_hash')
    # ### end Alembic commands ###
